//! Sonarr tool surface — `sonarr.*`. Thin wrappers over the shared
//! `crate::clients` base library.
//!
//! Tool surface (one-tool-per-resource):
//!
//! - `sonarr.{list, detail, create, update, delete}` — endpoint registry CRUD,
//!   generated by `endpoint_resource!` from the toolkit.
//! - `sonarr.health` — **detection.** Health issues from `/api/v3/health`.
//! - `sonarr.indexers` — configured indexers from `/api/v3/indexer`.
//! - `sonarr.test_indexers` — **remediation.** Re-test every indexer.
//! - `sonarr.system_status` — app name / version / instance.
//!
//! Sonarr speaks `/api/v3` with a `/series` media model; the [`Flavor`] is
//! fixed to `Sonarr`, so the endpoint row carries no `flavor` column.
//!
//! Imports flow through `plugin_toolkit::prelude::*` only.
#![allow(clippy::disallowed_types)]

use plugin_toolkit::prelude::*;

use crate::clients::{
    Client, Config, Flavor, HealthIssue, Indexer, IndexerTestResult, SystemStatus,
};

#[endpoint_resource(plugin = "sonarr")]
pub struct SonarrEndpoint {
    pub name: String,
    #[secret]
    pub api_key: String,
}

/// Resolve a registered Sonarr endpoint to a live [`Client`], picking the
/// first reachable address from the endpoint's fallback list.
async fn make_client(name: &str) -> Result<Client> {
    let row = {
        let conn = runtime::open_db()?;
        endpoint_db::get(&conn, name)?
            .with_context(|| format!("sonarr endpoint '{name}' not registered"))?
    };
    if !row.enabled {
        bail!("sonarr endpoint '{name}' is disabled");
    }
    let base_url = address::resolve_reachable(name, &row.addresses).await?;
    Ok(Client::new(Config::new(
        base_url,
        row.api_key,
        Flavor::Sonarr,
    )))
}

#[derive(
    plugin_toolkit::clap::Args,
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrHealthArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrHealthOutput {
    /// Total health issues raised.
    pub issue_count: usize,
    /// Health issues from `/health`.
    pub issues: Vec<HealthIssue>,
}

/// **Detection.** Health issues currently raised by a registered Sonarr server.
#[orca_tool(domain = "sonarr", verb = "health")]
async fn sonarr_health(args: SonarrHealthArgs, _ctx: &ToolCtx) -> Result<SonarrHealthOutput> {
    let issues = crate::clients::ops::health(&make_client(&args.endpoint).await?).await?;
    Ok(SonarrHealthOutput {
        issue_count: issues.len(),
        issues,
    })
}

#[derive(
    plugin_toolkit::clap::Args,
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrIndexersArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrIndexersOutput {
    /// Configured indexers from `/indexer`.
    pub indexers: Vec<Indexer>,
}

/// Configured indexers on a registered Sonarr server.
#[orca_tool(domain = "sonarr", verb = "indexers")]
async fn sonarr_indexers(args: SonarrIndexersArgs, _ctx: &ToolCtx) -> Result<SonarrIndexersOutput> {
    let indexers = crate::clients::ops::indexers(&make_client(&args.endpoint).await?).await?;
    Ok(SonarrIndexersOutput { indexers })
}

#[derive(
    plugin_toolkit::clap::Args,
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrTestIndexersArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrTestIndexersOutput {
    /// Indexers tested.
    pub tested_count: usize,
    /// Indexers that passed.
    pub valid_count: usize,
    /// Per-indexer result.
    pub results: Vec<IndexerTestResult>,
}

/// **Remediation.** Re-test every indexer on a registered Sonarr server,
/// clearing stale backoff so recovered indexers are used again immediately.
#[orca_tool(domain = "sonarr", verb = "test_indexers")]
async fn sonarr_test_indexers(
    args: SonarrTestIndexersArgs,
    _ctx: &ToolCtx,
) -> Result<SonarrTestIndexersOutput> {
    let results = crate::clients::ops::test_indexers(&make_client(&args.endpoint).await?).await?;
    let valid_count = results
        .iter()
        .filter(|r| r.is_valid.unwrap_or(false))
        .count();
    Ok(SonarrTestIndexersOutput {
        tested_count: results.len(),
        valid_count,
        results,
    })
}

#[derive(
    plugin_toolkit::clap::Args,
    plugin_toolkit::serde::Serialize,
    plugin_toolkit::serde::Deserialize,
    plugin_toolkit::schemars::JsonSchema,
)]
#[serde(crate = "plugin_toolkit::serde")]
#[schemars(crate = "plugin_toolkit::schemars")]
pub struct SonarrSystemStatusArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

/// App name, version, and instance name from `/system/status`.
#[orca_tool(domain = "sonarr", verb = "system_status")]
async fn sonarr_system_status(
    args: SonarrSystemStatusArgs,
    _ctx: &ToolCtx,
) -> Result<SystemStatus> {
    Ok(crate::clients::ops::system_status(&make_client(&args.endpoint).await?).await?)
}

// TODO: sonarr.add_series — Sonarr-specific media tool over `/api/v3/series`.
